---
language: python
python:
  - "3.8"
services: docker

install:
  # Install test dependencies.
  - pip install molecule yamllint ansible-lint docker==3.7.3

before_script:
  - ansible --version

script:
  # Run tests.
  - molecule test

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/