---
- name: Ensure all dependencies are satisfied
  include_tasks: composer.yml

- name: Install Drupal by configuration
  command: "{{ drupal_project_dir }}/bin/drush site:install -y --site-name=\"{{ drupal_site_name }}\" --site-mail=\"{{ drupal_site_mail }}\"
         --account-mail=\"{{ drupal_account_mail }}\" --account-name=\"{{ drupal_account_name }}\" --account-pass=\"{{ drupal_account_pass }}\"
         --existing-config"
  changed_when: False

- name: Check if locale is enabled
  shell: |
    set -o pipefail
    bin/drush pm:list --type module --format=csv | grep locale | awk -F, '{print $3}'
  args:
    executable: /bin/bash
    chdir: "{{ drupal_project_dir }}"
  register: locale_state
  changed_when: False

- name: Ensure locale configurations are checked
  command: "{{ drupal_project_dir }}/bin/drush locale:check -y"
  when:
    - locale_state == 'Enabled'

- name: Update locale traslations are updated
  command: "{{ drupal_project_dir }}/bin/drush locale:update -y"
  when:
    - locale_state == 'Enabled'

- name: Clear Drupal cache
  command: "{{ drupal_project_dir }}/bin/drush cr -y"
  changed_when: False