---
- name: Delete old /tmp/composer-project
  file:
    path: "/tmp/composer-project"
    state: absent

- name: Generate Drupal project with composer package in /tmp/composer-project (this may take a while).
  composer:
    command: create-project
    arguments: "{{ drupal_composer_project_package }} composer-project --stability dev --no-install"
    working_dir: /tmp
  environment:
    COMPOSER_PROCESS_TIMEOUT: 1200

- name: Ensure drupal_project_dir directory has proper permissions.
  file:
    path: "{{ drupal_project_dir }}"
    state: directory
    owner: "{{ drupal_project_owner }}"
    group: "{{ drupal_project_group }}"
    mode: 0775
  failed_when: false

- name: Remove .git folder
  file:
    path: "{{ drupal_project_dir }}/.git"
    state: absent

- name: Remove .gitignore file
  file:
    path: "{{ drupal_project_dir }}/.gitignore"
    state: absent

- name: Move Drupal project files to drupal_project_dir (this may take a while).
  command:
    cmd: "cp -r /tmp/composer-project/. {{ drupal_project_dir }}/"
    creates: "{{ drupal_project_dir }}/{{ drupal_project_web_root }}/index.php"
  become: false

- name: Create Bin directory
  file:
    path: "{{ drupal_project_dir }}/bin"
    state: directory
    mode: 0755

- name: Add Bin directory to composer config
  composer:
    command: config
    arguments: bin-dir bin/
    working_dir: "{{ drupal_project_dir }}"

- name: Create composer.patches.json
  copy:
    dest: "{{ drupal_project_dir }}/composer.patches.json"
    content: |
      {
        "patches": {
        }
      }

- name: Add composer.patches.json file to composer config
  composer:
    command: config
    arguments: extra.patches-file composer.patches.json
    working_dir: "{{ drupal_project_dir }}"
