---
# tasks file for ansible-role-drupal
- ansible.builtin.include_tasks: setup.yml
  tags: [ 'setup' ]

- ansible.builtin.include_tasks: "{{ drupal_before_create | default('empty.yml') }}"
  tags: [ 'create' ]
  when:
    - not drupal_site_exists

- ansible.builtin.include_tasks: create.yml
  tags: [ 'create' ]
  when:
    - not drupal_site_exists

- ansible.builtin.include_tasks: "{{ drupal_after_create | default('empty.yml') }}"
  tags: [ 'create' ]
  when:
    - not drupal_site_exists

- ansible.builtin.include_tasks: "{{ drupal_before_install | default('empty.yml') }}"
  tags: [ 'install' ]
  when:
    - not drupal_config_exists

- ansible.builtin.include_tasks: install.yml
  tags: [ 'install' ]
  when:
    - not drupal_config_exists

- ansible.builtin.include_tasks: "{{ drupal_after_install | default('empty.yml') }}"
  tags: [ 'install' ]
  when:
    - not drupal_config_exists

- ansible.builtin.include_tasks: "{{ drupal_before_build | default('empty.yml') }}"
  tags: [ 'build' ]
  when:
    - drupal_config_exists

- ansible.builtin.include_tasks: build.yml
  tags: [ 'build' ]
  when:
    - drupal_config_exists

- ansible.builtin.include_tasks: "{{ drupal_after_build | default('empty.yml') }}"
  tags: [ 'build' ]
  when:
    - drupal_config_exists