---
- name: Ensure if Drupal project exists
  ansible.builtin.stat:
    path: "{{ drupal_project_dir }}/{{ drupal_project_web_root }}/index.php"
  register: __drupal_project_exists
  ignore_errors: true

- name: Define drupal_site_exists.
  ansible.builtin.set_fact:
    drupal_site_exists: "{{ __drupal_project_exists.stat.exists | default(false) }}"

- name: Ensure if Drupal config exists
  ansible.builtin.stat:
    path: "{{ drupal_project_dir }}/config/sync/system.site.yml"
  register: __drupal_config_exists
  ignore_errors: true

- name: Define drupal_config_exists
  ansible.builtin.set_fact:
    drupal_config_exists: "{{ __drupal_config_exists.stat.exists | default(false) }}"