mysql_python_package_debian: python3-mysqldb
mysql_daemon: mysql
mysql_databases:
  - name: "{{ drupal_db_name }}"
    encoding: utf8mb4
    collation: utf8mb4_general_ci
mysql_users:
  - name: "{{ drupal_db_user }}"
    host: "%"
    password: "{{ drupal_db_pass }}"
    priv: "{{ drupal_db_name }}.*:ALL"

## Drupal install/build settings
drupal_db_schema: "mysql"
drupal_db_name: "drupal"
drupal_db_user: "drupal"
drupal_db_pass: "drupal"
drupal_db_host: "127.0.0.1"
drupal_db_port: "3306"
drupal_db_url: "{{ drupal_db_schema }}://{{ drupal_db_user }}:{{ drupal_db_pass }}@{{ drupal_db_host }}:{{ drupal_db_port }}/{{ drupal_db_name }}"
drupal_composer_allow_plugin: true
drupal_composer_nodev: false
drupal_composer_prefer_dist: false
drupal_composer_scaffold: false
drupal_composer_scaffold_namespace: false