---
- name: Converge
  hosts: all

  environment:
    COMPOSER_MEMORY_LIMIT: '-1'

  vars_files:
    - converge-vars.yml

  roles:
    - { role: geerlingguy.mysql }
    - { role: bmeme.drupal }

  tasks:
    - name: Re-exec role
      ansible.builtin.include_role:
        name: bmeme.drupal
