---
name: Ansible Role Drupal CI
'on':
  pull_request:
  push:
    branches:
      - master
      - main

defaults:
  run:
    working-directory: 'bmeme.drupal'

jobs:

  lint:
    name: Lint
    runs-on: ubuntu-latest
    steps:
      -
        name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'bmeme.drupal'
      -
        name: Run yamllint
        uses: karancode/yamllint-github-action@master
        with:
          yamllint_config_filepath: '${{ github.workspace }}/bmeme.drupal/.yamllint'
      -
        name: Setup ansible-lint
        uses: bec-galaxy/setup-lint@v1
      -
        name: Run ansible-lint
        run: |
          ansible-galaxy install -r requirements.yml; \
          ansible-lint .

  molecule:
    name: Run molecule test
    runs-on: ubuntu-latest
    needs: [lint]
    steps:
      - 
        name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'bmeme.drupal'
      -
        name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      -
        name: Install dependencies.
        run: pip3 install ansible molecule-plugins[docker] docker
      - 
        name: Run Molecule tests.
        run: molecule test
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
