---
# This workflow requires a GALAXY_API_KEY secret present in the GitHub
# repository or organization.
#
# See: https://github.com/marketplace/actions/publish-ansible-role-to-galaxy

name: Ansible Role Drupal Release
'on':
  push:
    tags:
      - '*'

defaults:
  run:
    working-directory: 'bmeme.drupal'

jobs:

  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - 
        name: Check out the codebase.
        uses: actions/checkout@v4
        with:
          path: 'bmeme.drupal'

      - 
        name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - 
        name: Install Ansible.
        run: pip3 install ansible-base

      - 
        name: Trigger a new import on Galaxy.
        run: |
          {
            ansible-galaxy role import \
              --api-key ${{ secrets.GALAXY_API_KEY }} $(echo ${{ github.repository }} |\
               cut -d/ -f1) $(echo ${{ github.repository }} | cut -d/ -f2)
          }